default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV["DATABASE_NAME"] %>
  host: <%= ENV["DATABASE_HOST"] %>
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  port: <%= ENV["DATABASE_PORT"] %>

test:
  <<: *default
  database: birthday_reminder_test

production:
  <<: *default
  database: birthday_reminder_production
  username: birthday_reminder
  password: <%= ENV["BIRTHDAY_REMINDER_DATABASE_PASSWORD"] %>
